package com.ml.widgets.widget.background_cardcarousel.type_one;

/**
 * Created by jcace on 17/10/2016.
 */

public class WidgetBackgroundCardCarousel_TypeOne_Constants {

    /******************************* TITLE ******************************/
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_INDEX_TYPE = 0;
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_INDEX_STYLE = 1;
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_INDEX_GRAVITY = 2;
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_INDEX_SIZE = 3;
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_INDEX_COLOR = 4;
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_INDEX_HEIGHT = 1;
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_INDEX_IMAGE = 3;
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_INDEX_TEXT = 0;
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_INDEX_PATH = 0;
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_INDEX_TYPEFACE = 1;
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_INDEX_GRAVITY_SEPARATOR = 1;
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_INDEX_NUM_SEPARATOR = 2;

    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_SIZE_TEXT_VALUES_INT = 5;
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_SIZE_TEXT_VALUES_STRING = 2;

    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_VALUE_TYPE_TEXT = 1;
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_VALUE_TYPE_IMAGE = 2;
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_VALUE_TYPE_SEPARATOR = 3;

    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_VALUE_GRAVITY_START = 1;
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_VALUE_GRAVITY_END = 2;

    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_VALUE_STYLE_NORMAL = 1;
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_VALUE_STYLE_BOLD = 2;
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_VALUE_STYLE_ITALIC = 3;
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_VALUE_STYLE_BOLDITALIC = 4;
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_VALUE_STYLE_STRIKETHROUGH = 5;

    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_SIZE_IMAGE_MAX_VALUES_INT = 4;
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_SIZE_IMAGE_MAX_VALUES_STRING = 1;

    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_TITLE_SIZE_SEPARATOR_VALUES_INT = 3;

    /******************************* CONFIG ******************************/
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_CONFIG_SIZE_MAX_VALUES_INT = 3;
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_CONFIG_SIZE_MAX_VALUES_STRING = 1;

    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_CONFIG_INDEX_RESOURCE = 2;
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_CONFIG_INDEX_PATH = 0;

    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_CONFIG_INDEX_TITLECOUNT = 0;
    public static final int WIDGET_BACKGROUND_CARDCAROUSEL_TYPEONE_CONFIG_INDEX_OFFSET = 1;

}
